# QF627 Pre-Course Workshop | Introduction to Programming
## Lesson 04 | An Introduction to `pandas` Part 1 | `RE`view

> Let's learn `pandas`!

> `pandas` is one of the most powerful and popular tools in dealing with data within Python.

> In finance, familiarity with pandas is essential. 

> We will work with real-world datasets containing both string and numeric data, often structured around time series.

> You will learn effective data manipulation, analysis, and visualization techniques with pandas.

> First, you will learn

- how to open and read in a csv spreadsheet
- how to look at the data we have
- how to select columns
- how to do some simple math with them


In [1]:
%whos

Interactive namespace is empty.


> First we need to `import pandas as a library`. We import the library and then tell Python to refer to it as `pd`. By convention, it's imported as `pd` to save typing.

In [2]:
import pandas as pd

import matplotlib.pyplot as plt

import numpy as np

In [3]:
import sys

In [4]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd         module    <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
plt        module    <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
sys        module    <module 'sys' (built-in)>


In [5]:
sys\
    .path

['/Users/sroh/Desktop/qf627',
 '/Users/sroh/miniforge3/envs/rohenv/lib/python39.zip',
 '/Users/sroh/miniforge3/envs/rohenv/lib/python3.9',
 '/Users/sroh/miniforge3/envs/rohenv/lib/python3.9/lib-dynload',
 '',
 '/Users/sroh/miniforge3/envs/rohenv/lib/python3.9/site-packages']

In [6]:
pd\
    .__path__

['/Users/sroh/miniforge3/envs/rohenv/lib/python3.9/site-packages/pandas']

## IMPORT

### Reading spreadsheets

> This is how you read a spreadsheet and assign it to an object. Reading in a CSV is just as easy as you'd guess.

In [7]:
%ls

2016_census_data.csv
Exercise_Data_April.csv
Exercise_Data_August.csv
Exercise_Data_December.csv
Exercise_Data_February.csv
Exercise_Data_January.csv
Exercise_Data_July.csv
Exercise_Data_June.csv
Exercise_Data_March.csv
Exercise_Data_May.csv
Exercise_Data_November.csv
Exercise_Data_October.csv
Exercise_Data_September.csv
QF627_PreCourse_01_Introduction_REview.ipynb
QF627_PreCourse_02_NumPy_REview.ipynb
QF627_PreCourse_03_matplotlib_InProgress_2.ipynb
QF627_PreCourse_04_pandas_Part1_Preview.ipynb
QF627_PreCourse_04_pandas_Part2_Preview.ipynb
QF627_PreCourse_Problem_Sets.ipynb
countries.csv
matplotlib.png
ndim.png
players.csv
plot_with_shapes.png
salaries.csv


In [8]:
tabular_data =\
(
    pd
    .read_csv("2016_census_data.csv")
)

tabular_data

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,Census Tract 10,Bergen County,New Jersey,6767,151641,680000,3045,5667,75,0,759,0,0,132,134
1,34003002100,Census Tract 21,Bergen County,New Jersey,1522,114545,2000001,836,788,141,0,444,0,0,27,122
2,34003002200,Census Tract 22,Bergen County,New Jersey,5389,90647,453800,1791,3481,99,9,1247,0,36,19,504
3,34003002300,Census Tract 23,Bergen County,New Jersey,5828,112031,610000,2363,3595,89,37,1627,0,0,32,448
4,34003003100,Census Tract 31,Bergen County,New Jersey,4946,76906,301900,1588,1803,306,0,1435,0,13,24,1365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4695,42103950701,Census Tract 9507.01,Pike County,Pennsylvania,4107,61726,155800,537,3665,12,0,67,0,0,26,337
4696,42103950702,Census Tract 9507.02,Pike County,Pennsylvania,3119,59239,151100,405,2908,44,0,60,0,0,19,88
4697,42103950801,Census Tract 9508.01,Pike County,Pennsylvania,4403,55530,120000,718,2777,705,0,53,0,0,97,771
4698,42103950802,Census Tract 9508.02,Pike County,Pennsylvania,6004,50724,146700,795,3072,970,20,44,0,0,11,1887


### tabular data ==> 2 dimensional data

|dimension |  built-in Python | numpy     | pandas     |
|----------|------------------|-----------|------------|
|1 D       | list             | 1d-array  | Series     |
|2 D       | nested list      | 2d-array  | DataFrame  |

### Built-in Python List

In [9]:
list_with_integers = [6, 2, 7, 100]

In [10]:
type(list_with_integers)

list

In [11]:
list_with_integers * 3

[6, 2, 7, 100, 6, 2, 7, 100, 6, 2, 7, 100]

### NumPy

In [13]:
array_with_integers =\
(
    np
    .array(list_with_integers)
)

array_with_integers

array([  6,   2,   7, 100])

In [14]:
array_with_integers * 3

array([ 18,   6,  21, 300])

In [15]:
type(array_with_integers)

numpy.ndarray

#### 2d-array for Data Frame

In [17]:
# 1d-array 

values_0_to_39 = np.arange(40)
values_0_to_39

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [18]:
values_0_to_39.ndim

1

In [20]:
values_0_to_39_2D =\
(
    # np
    # .arange(40)
    values_0_to_39
    .reshape(5, -1)
    # -1: degree of freedom
)

values_0_to_39_2D.ndim == 2

True

In [22]:
values_0_to_39_2D \
    .mean()

19.5

In [23]:
values_0_to_39_2D \
    .mean(axis = 0)

array([16., 17., 18., 19., 20., 21., 22., 23.])

## with Pandas

In [24]:
numpy_2d_array =\
(
    np
    .arange(15)
    .reshape(3, 5)
)

In [25]:
dir(numpy_2d_array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [26]:
# .values IS READY

numpy_2d_array.T # Transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [28]:
# .index (with time-series)

index =\
(
    pd
    .date_range("2024-08-21",
                periods = 5,
                freq = "B")
)

index

DatetimeIndex(['2024-08-21', '2024-08-22', '2024-08-23', '2024-08-26',
               '2024-08-27'],
              dtype='datetime64[ns]', freq='B')

In [29]:
list("BTS") == ["B", "T", "S"]

True

In [30]:
np.array(list("BTS")) == np.array(["B", "T", "S"])

array([ True,  True,  True])

In [31]:
columns = list("BTS")

columns

['B', 'T', 'S']

In [33]:
numpy_2d_array.size

15

In [37]:
our_pandas_dataframe =\
(
    pd
    .DataFrame(numpy_2d_array.T,
               index = index, # 5 elements
               columns = columns # 3 element
              )
)
    
our_pandas_dataframe

,B,T,S
2024-08-21,0,5,10
2024-08-22,1,6,11
2024-08-23,2,7,12
2024-08-26,3,8,13
2024-08-27,4,9,14


In [38]:
our_pandas_dataframe["B"] # indexing

2024-08-21    0
2024-08-22    1
2024-08-23    2
2024-08-26    3
2024-08-27    4
Freq: B, Name: B, dtype: int64

In [39]:
our_pandas_dataframe.B # . accessor

2024-08-21    0
2024-08-22    1
2024-08-23    2
2024-08-26    3
2024-08-27    4
Freq: B, Name: B, dtype: int64

In [40]:
dir(our_pandas_dataframe)

['B',
 'S',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '_

In [41]:
our_pandas_dataframe["T"] == our_pandas_dataframe.T

,2024-08-21,2024-08-22,2024-08-23,2024-08-26,2024-08-27
B,False,False,False,False,False
T,True,True,True,True,True
S,False,False,False,False,False


In [42]:
our_pandas_dataframe["T"]

2024-08-21    5
2024-08-22    6
2024-08-23    7
2024-08-26    8
2024-08-27    9
Freq: B, Name: T, dtype: int64

In [43]:
our_pandas_dataframe.T

,2024-08-21,2024-08-22,2024-08-23,2024-08-26,2024-08-27
B,0,1,2,3,4
T,5,6,7,8,9
S,10,11,12,13,14


In [47]:
type(our_pandas_dataframe["T"]) # returns Series

pandas.core.series.Series

In [48]:
type(our_pandas_dataframe[["T"]]) # returns DataFrame

pandas.core.frame.DataFrame

In [45]:
our_pandas_dataframe[["T", "S"]]

,T,S
2024-08-21,5,10
2024-08-22,6,11
2024-08-23,7,12
2024-08-26,8,13
2024-08-27,9,14


In [50]:
our_pandas_dataframe.index

DatetimeIndex(['2024-08-21', '2024-08-22', '2024-08-23', '2024-08-26',
               '2024-08-27'],
              dtype='datetime64[ns]', freq='B')

In [51]:
our_pandas_dataframe_with_column_date =\
(
    our_pandas_dataframe
    .reset_index()
)

our_pandas_dataframe_with_column_date

,index,B,T,S
0,2024-08-21,0,5,10
1,2024-08-22,1,6,11
2,2024-08-23,2,7,12
3,2024-08-26,3,8,13
4,2024-08-27,4,9,14


In [52]:
our_pandas_dataframe_with_column_date =\
(
    our_pandas_dataframe_with_column_date
    .rename(columns = {"index": "date"}
           )          # "old" : "new"
)

our_pandas_dataframe_with_column_date

,date,B,T,S
0,2024-08-21,0,5,10
1,2024-08-22,1,6,11
2,2024-08-23,2,7,12
3,2024-08-26,3,8,13
4,2024-08-27,4,9,14


In [54]:
our_pandas_dataframe_with_column_date \
    .pivot(index = "B",
           columns = "date")\
    .columns

MultiIndex([('T', '2024-08-21'),
            ('T', '2024-08-22'),
            ('T', '2024-08-23'),
            ('T', '2024-08-26'),
            ('T', '2024-08-27'),
            ('S', '2024-08-21'),
            ('S', '2024-08-22'),
            ('S', '2024-08-23'),
            ('S', '2024-08-26'),
            ('S', '2024-08-27')],
           names=[None, 'date'])

In [55]:
our_pandas_dataframe_with_column_date\
    .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   date    5 non-null      datetime64[ns]
 1   B       5 non-null      int64         
 2   T       5 non-null      int64         
 3   S       5 non-null      int64         
dtypes: datetime64[ns](1), int64(3)
memory usage: 288.0 bytes


In [56]:
our_pandas_dataframe_with_column_date.shape

(5, 4)

In [58]:
type(our_pandas_dataframe_with_column_date.values)

numpy.ndarray

In [59]:
our_pandas_dataframe_with_column_date.values.ndim

2

In [61]:
(
    our_pandas_dataframe_with_column_date
    .isnull() # vectorized computing
    .sum() # False being 0; True being 1
)

date    0
B       0
T       0
S       0
dtype: int64

In [63]:
our_pandas_dataframe_with_column_date \
    .head(3)

,date,B,T,S
typing.Literal[<no_default>],,,,
0,2024-08-21,0,5,10
1,2024-08-22,1,6,11
2,2024-08-23,2,7,12


In [64]:
our_pandas_dataframe_with_column_date \
    .tail()

,date,B,T,S
typing.Literal[<no_default>],,,,
0,2024-08-21,0,5,10
1,2024-08-22,1,6,11
2,2024-08-23,2,7,12
3,2024-08-26,3,8,13
4,2024-08-27,4,9,14


### Looking at your data

> To look at the data you just read into Python, you can just run a cell with the name of the variable:

In [65]:
%whos

Variable                                Type             Data/Info
------------------------------------------------------------------
array_with_integers                     ndarray          4: 4 elems, type `int64`, 32 bytes
columns                                 list             n=3
index                                   DatetimeIndex    DatetimeIndex(['2024-08-2<...>atetime64[ns]', freq='B')
list_with_integers                      list             n=4
np                                      module           <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy_2d_array                          ndarray          3x5: 15 elems, type `int64`, 120 bytes
our_pandas_dataframe                    DataFrame                    B  T   S\n202<...> 13\n2024-08-27  4  9  14
our_pandas_dataframe_with_column_date   DataFrame                                 <...>     2024-08-27  4  9  14
pd                                      module           <module 'pandas' from '/U<...>ages/pandas/__ini

In [67]:
tabular_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4700 entries, 0 to 4699
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype 
---  ------                            --------------  ----- 
 0   geoid                             4700 non-null   int64 
 1   name                              4700 non-null   object
 2   county                            4700 non-null   object
 3   state                             4700 non-null   object
 4   total_population                  4700 non-null   int64 
 5   median_income                     4700 non-null   int64 
 6   median_home_value                 4700 non-null   int64 
 7   educational_attainment            4700 non-null   int64 
 8   white_alone                       4700 non-null   int64 
 9   black_alone                       4700 non-null   int64 
 10  native                            4700 non-null   int64 
 11  asian                             4700 non-null   int64 
 12  native_hawaiian_paci

In [69]:
tabular_data.head(10)

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
0,34003001000,Census Tract 10,Bergen County,New Jersey,6767,151641,680000,3045,5667,75,0,759,0,0,132,134
1,34003002100,Census Tract 21,Bergen County,New Jersey,1522,114545,2000001,836,788,141,0,444,0,0,27,122
2,34003002200,Census Tract 22,Bergen County,New Jersey,5389,90647,453800,1791,3481,99,9,1247,0,36,19,504
3,34003002300,Census Tract 23,Bergen County,New Jersey,5828,112031,610000,2363,3595,89,37,1627,0,0,32,448
4,34003003100,Census Tract 31,Bergen County,New Jersey,4946,76906,301900,1588,1803,306,0,1435,0,13,24,1365
5,34003003200,Census Tract 32,Bergen County,New Jersey,5044,69531,322400,1417,1342,186,19,1882,0,6,64,1564
6,34003003300,Census Tract 33,Bergen County,New Jersey,6638,97957,328100,1737,2437,400,0,2131,0,0,148,1522
7,34003003401,Census Tract 34.01,Bergen County,New Jersey,2958,122650,385200,941,1704,109,0,520,0,0,36,589
8,34003003402,Census Tract 34.02,Bergen County,New Jersey,3827,105776,356100,1237,1937,260,0,733,0,4,122,771
9,34003003500,Census Tract 35,Bergen County,New Jersey,4100,52382,340200,891,886,502,16,1160,0,0,59,1493


> Oops, that's a little long. Maybe we just want to see the first 10 rows:

In [70]:
tabular_data.tail()

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino
4695,42103950701,Census Tract 9507.01,Pike County,Pennsylvania,4107,61726,155800,537,3665,12,0,67,0,0,26,337
4696,42103950702,Census Tract 9507.02,Pike County,Pennsylvania,3119,59239,151100,405,2908,44,0,60,0,0,19,88
4697,42103950801,Census Tract 9508.01,Pike County,Pennsylvania,4403,55530,120000,718,2777,705,0,53,0,0,97,771
4698,42103950802,Census Tract 9508.02,Pike County,Pennsylvania,6004,50724,146700,795,3072,970,20,44,0,0,11,1887
4699,42103950900,Census Tract 9509,Pike County,Pennsylvania,4184,49453,146100,721,3888,55,29,22,0,0,9,181


> Or you might want to look at the last five:

In [72]:
tabular_data.shape[0] == len(tabular_data)

True

> or you want to know the length of the entire set:

In [71]:
len(tabular_data) == 4699 + 1

True

### Filtering by columns

> How about filtering your data by columns? This is how you can do that:

In [74]:
tabular_data\
    .columns\
    .to_frame()

,0
geoid,geoid
name,name
county,county
state,state
total_population,total_population
median_income,median_income
median_home_value,median_home_value
educational_attainment,educational_attainment
white_alone,white_alone
black_alone,black_alone


In [75]:
tabular_data\
    .state

0          New Jersey
1          New Jersey
2          New Jersey
3          New Jersey
4          New Jersey
            ...      
4695     Pennsylvania
4696     Pennsylvania
4697     Pennsylvania
4698     Pennsylvania
4699     Pennsylvania
Name: state, Length: 4700, dtype: object

> Often, you might want to select multiple columns:

In [80]:
referece_to_two_vars = ["state", "county"]

(tabular_data[["state", "county"]] == tabular_data[referece_to_two_vars])\
    .value_counts()\
    .to_frame()

,,count
state,county,
True,True,4700


In [76]:
tabular_data[["state", "county"]]

,state,county
0,New Jersey,Bergen County
1,New Jersey,Bergen County
2,New Jersey,Bergen County
3,New Jersey,Bergen County
4,New Jersey,Bergen County
...,...,...
4695,Pennsylvania,Pike County
4696,Pennsylvania,Pike County
4697,Pennsylvania,Pike County
4698,Pennsylvania,Pike County


### Doing simple math with your data
> There are a few nifty functions you can apply to your data columns. 

In [81]:
tabular_data.columns

Index(['geoid', 'name', 'county', 'state', 'total_population', 'median_income',
       'median_home_value', 'educational_attainment', 'white_alone',
       'black_alone', 'native', 'asian', 'native_hawaiian_pacific_islander',
       'some_other_race_alone', 'two_or_more', 'hispanic_or_latino'],
      dtype='object')

> There is also this nifty function which gives you a quick overview of your data:

In [82]:
(
    tabular_data
    .total_population
    .sum()
)

20031443

In [83]:
(
    tabular_data # DF
    #.total_population
    ["total_population"] # Series
    .sum() # summation
)

20031443

In [84]:
(
    tabular_data
    [['total_population', 
      'median_income',
       'median_home_value']]
    .sum()
)

total_population         20031443
median_income        -59651916985
median_home_value   -187218190322
dtype: int64

In [86]:
(
    tabular_data
    [['total_population', 
      'median_income',
       'median_home_value']]
    .mean()
).to_frame()

,0
total_population,4.262009e+03
median_income,-1.269190e+07
median_home_value,-3.983366e+07


### Descriptive statistic, using .describe()

In [87]:
(
    tabular_data
    [['total_population', 
      'median_income',
       'median_home_value']]
    .describe()
)

,total_population,median_income,median_home_value
count,4700.000000,4.700000e+03,4.700000e+03
mean,4262.009149,-1.269190e+07,-3.983366e+07
std,2031.766771,9.138565e+07,1.589803e+08
min,0.000000,-6.666667e+08,-6.666667e+08
25%,2865.000000,4.652675e+04,2.914750e+05
50%,4082.500000,6.894450e+04,4.065000e+05
75%,5444.000000,9.595675e+04,5.648250e+05
max,29256.000000,2.500010e+05,2.000001e+06


$$ UpperBound = Q_3 + 1.5 \times (Q_3 - Q_1) $$

$$ LowerBound = Q_1 - 1.5 \times (Q_3 - Q_1) $$

### Making new data columns
> You can make a new column based on two columns like so:

In [89]:
tabular_data.columns

Index(['geoid', 'name', 'county', 'state', 'total_population', 'median_income',
       'median_home_value', 'educational_attainment', 'white_alone',
       'black_alone', 'native', 'asian', 'native_hawaiian_pacific_islander',
       'some_other_race_alone', 'two_or_more', 'hispanic_or_latino'],
      dtype='object')

> To overwrite your previous data you can just re-assign the column new values, the way you do with any variable: 

In [ ]:
# tabular_data["asian_prop"] = tabular_data["asian"] / tabular_data.total_population * 100

In [90]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [91]:
tabular_data["asian_prop"] =\
( # flow programming (chaining)
    tabular_data.asian
    /
    tabular_data.total_population
    * 100
)

##### A quick sorting function can now help you find the spots with the highest or lowest black populations (we can go over this again next week):

In [ ]:
(
    tabular_data
    [["asian_prop", "state"]]
    .sort_values(by = "asian_prop") # team, by default, it's ascending order.
)

In [94]:
(
    tabular_data
    [["asian_prop", "state"]]
    .sort_values(by = "asian_prop",
                 ascending = False)
)

,asian_prop,state
3811,89.488055,New York
1944,86.130268,New York
3819,84.900146,New York
2912,83.912249,New York
3509,82.055906,New York
...,...,...
3960,NaN,New York
4017,NaN,New York
4070,NaN,New York
4458,NaN,New York


### Grouping your data results

> `.groupby()`

In [95]:
tabular_data

,geoid,name,county,state,total_population,median_income,median_home_value,educational_attainment,white_alone,black_alone,native,asian,native_hawaiian_pacific_islander,some_other_race_alone,two_or_more,hispanic_or_latino,asian_prop
0,34003001000,Census Tract 10,Bergen County,New Jersey,6767,151641,680000,3045,5667,75,0,759,0,0,132,134,11.216196
1,34003002100,Census Tract 21,Bergen County,New Jersey,1522,114545,2000001,836,788,141,0,444,0,0,27,122,29.172142
2,34003002200,Census Tract 22,Bergen County,New Jersey,5389,90647,453800,1791,3481,99,9,1247,0,36,19,504,23.139729
3,34003002300,Census Tract 23,Bergen County,New Jersey,5828,112031,610000,2363,3595,89,37,1627,0,0,32,448,27.916953
4,34003003100,Census Tract 31,Bergen County,New Jersey,4946,76906,301900,1588,1803,306,0,1435,0,13,24,1365,29.013344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4695,42103950701,Census Tract 9507.01,Pike County,Pennsylvania,4107,61726,155800,537,3665,12,0,67,0,0,26,337,1.631361
4696,42103950702,Census Tract 9507.02,Pike County,Pennsylvania,3119,59239,151100,405,2908,44,0,60,0,0,19,88,1.923693
4697,42103950801,Census Tract 9508.01,Pike County,Pennsylvania,4403,55530,120000,718,2777,705,0,53,0,0,97,771,1.203725
4698,42103950802,Census Tract 9508.02,Pike County,Pennsylvania,6004,50724,146700,795,3072,970,20,44,0,0,11,1887,0.732845


In [96]:
(
    tabular_data
    .asian_prop
    .mean()
)

10.517544752040978

In [98]:
(
    tabular_data
    .groupby(["state"]) # re-set unit of analysis at state-level
    .asian_prop
    .mean()
).to_frame()

,asian_prop
state,
New Jersey,9.725673
New York,10.927506
Pennsylvania,1.056677


In [99]:
(
    tabular_data
    .groupby(["county"]) # re-set unit of analysis at `county`-level
    .asian_prop
    .mean()
)

county
 Bergen County         16.034681
 Bronx County           3.771159
 Dutchess County        3.606760
 Essex County           4.111863
 Hudson County         14.618640
 Hunterdon County       3.430046
 Kings County          11.329430
 Middlesex County      22.100983
 Monmouth County        4.531849
 Morris County          9.912594
 Nassau County          8.552710
 New York County       12.392477
 Ocean County           1.742117
 Orange County          2.493452
 Passaic County         4.924141
 Pike County            1.056677
 Putnam County          2.030521
 Queens County         23.128775
 Richmond County        7.688357
 Rockland County        6.076602
 Somerset County       14.321779
 Suffolk County         3.667987
 Sussex County          1.992591
 Union County           4.456520
 Westchester County     5.685249
Name: asian_prop, dtype: float64

> `.agg()`

    recall that between dict. and list, dict. is more pythonian data type!

In [100]:
(
    tabular_data
    .groupby(["state"])
    .agg({"asian_prop": "mean"}
        )
)

,asian_prop
state,
New Jersey,9.725673
New York,10.927506
Pennsylvania,1.056677


`Thank you for working with the script.`