# QF627 Pre-Course Workshop | Introduction to Programming

## Lesson 2 | An Introduction to `NumPy` | `In Progress` `2`

> In the previous lesson, you have learned about `methods and functions` that are available in built-in Python, along with variables and data types.

> First, let us begin with some basic built-in Python that you need to fully understand before we proceed.

> Here's a quick reminder regarding the useful hotkeys for scripting on Jupyter Notebook :)

- `a` inserts a cell above 
- `b` inserts a cell below
- `dd` (double d) deletes a cell 
- `esc` jumps out of the cell
- `return/enter` gets into the cell
- `m` makes your cell markdown
- `y` makes your cell code
- `shift + control + -` splits the cell
- `shift + m` merges the cells
- `shift + l` adds line numbers into the cell

> Now you will start learning about how to use `packages`.

> As Python is open-source language, using the humongous ecosystem of packages will help you work more efficiently.

> A `package is a collection of Python modules and scripts` giving you new data types, functions, and methods.


### How to `install` a ***package***?

> To use a package, you need to download it first.

> Let's use the command `pip3 install target_package` so that you can install packages of your interest.

> For downloading a package, you need to do this just once, yet you should import in your workspace whenever you wish to use it.

> The command below will load the NumPy package into Python for your use.

In [1]:
# !pip install numpy # numerical computation


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [2]:
# !pip install pandas # data transformation and manipulation of tabular data


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [4]:
# !pip install matplotlib # matlab-like plotting


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [5]:
# !pip install seaborn # visualization with modeling information


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [6]:
# !pip install statsmodels # modeling for explanation purposes (B-hat Questions) ==> Causal Inference


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [7]:
# !pip install scikit-learn # scipy-toolkit for machine learning; modeling for prediction purposes (Y-hat Questions) ==> Machine Learning


[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [1]:
%whos

Interactive namespace is empty.


In [2]:
import numpy

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
numpy      module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [4]:
dir(numpy)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [6]:
import numpy as np

In [7]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy      module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [8]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [9]:
help(np.argsort)

Help on _ArrayFunctionDispatcher in module numpy:

argsort(a, axis=-1, kind=None, order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           T

In [10]:
np.argsort?

Signature:       np.argsort(a, axis=-1, kind=None, order=None)
Call signature:  np.argsort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function argsort at 0x10646cee0>
File:            ~/miniforge3/envs/rohenv/lib/python3.9/site-packages/numpy/core/fromnumeric.py
Docstring:      
Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified
by the `kind` keyword. It returns an array of indices of the same shape as
`a` that index data along the given axis in sorted order.

Parameters
----------
a : array_like
    Array to sort.
axis : int or None, optional
    Axis along which to sort.  The default is -1 (the last axis). If None,
    the flattened array is used.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the
    actual implementation

***Wait, why do we use alias here (i.e., as `np`)? ?*** 

> As you will see below, 

- To access the array() function, you need to use np.array() to indicate that the function is from the NumPy package.

> Yes, the reason why we have used np as alias is to minimize our typing task.

### The Basics

> Using `NumPy`, you can create a new data type called `array`.

> Why use data type `array`?

**`array` is useful for financial analysis because...**

- array `stores` data more efficiently

- array `performs` faster than built-in Python lists in terms of computations (access in reading and writing items faster as the package is optimized for numerical analyses)

- array `shows` better performance with relatively larger datasets

- array, most importantly, **`enables` you to utilize `array-related functions`**--you can perform statistical modelling and visualization easier, which is critical for financial analysis.





> **A good way to understand about the usefulness of NumPy is to compare array with list (yes, that list that you learned in the previous lesson).**

#### Differences 1. Arrays can contain only a single data type (unlike lists).

In [1]:
sample_list =\
    ["Quant",
     "Yes",
     True,
     1e9,
     627]

In [12]:
len(sample_list) == 5

True

In [13]:
type(sample_list)

list

> As you will see below, arrays in NumPy will convert the elements in the list to the most compatible data types.

In [14]:
sample_array =\
(
    np
    .array(sample_list)
)

In [15]:
type(sample_array)

numpy.ndarray

In [16]:
sample_array

array(['Quant', 'Yes', 'True', '1000000000.0', '627'], dtype='<U32')

In [17]:
# Here are lists.
earnings_list = [10.09, 10.28, 2.21, 6.19, 8.24]
prices_list = [99.98, 87.68, 154.23, 162.12, 121.11]

> How would you make objects `earnings` and `prices` arrays?

In [18]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [19]:
earnings_array = np.array([10.09, 10.28, 2.21, 6.19, 8.24])

In [20]:
%whos

Variable         Type       Data/Info
-------------------------------------
earnings_array   ndarray    5: 5 elems, type `float64`, 40 bytes
earnings_list    list       n=5
np               module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy            module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
prices_list      list       n=5
sample_array     ndarray    5: 5 elems, type `<U32`, 640 bytes
sample_list      list       n=5


In [21]:
prices_array = np.array(prices_list)

In [22]:
print(earnings_array);print(prices_array)

[10.09 10.28  2.21  6.19  8.24]
[ 99.98  87.68 154.23 162.12 121.11]


#### Differences 2. Arrays have different ways of operations (than lists).

> Let's see how lists behave first.

In [23]:
prices_list

[99.98, 87.68, 154.23, 162.12, 121.11]

In [24]:
earnings_list

[10.09, 10.28, 2.21, 6.19, 8.24]

In [25]:
addition_of_the_two_lists = prices_list + earnings_list
len(addition_of_the_two_lists)

10

> The two objects were merely concatenated. That's not what we want...

In [26]:
addition_of_the_two_lists

[99.98, 87.68, 154.23, 162.12, 121.11, 10.09, 10.28, 2.21, 6.19, 8.24]

> ***Arrays allow for efficient numerical manipulation of its elements.***

> Let's calculate `the dollar amount an investor can expect to invest in a company to receive one dollar of that company’s earnings`--yes, the `price to earnings ratio`--using two arrays, earnings_array and prices_array above.

In [27]:
pe_ratio_array = prices_array / earnings_array
len(pe_ratio_array)

5

In [28]:
print(pe_ratio_array)

[ 9.90882061  8.52918288 69.78733032 26.19063005 14.69781553]


> You could see here that arrays perform `element-wise mathematical operations`.

### Element-wise Operation with Built-in Python 

> List comprehension

```python
    [expression for item in iterable if condition]

In [29]:
square_of_items =\
    [number ** 2 for number in range(12) if number % 2 == 0]

square_of_items

[0, 4, 16, 36, 64, 100]

In [30]:
element_wise_operation =\
    [x / y for x, y in zip(prices_list, earnings_list)
    ]

element_wise_operation

[9.908820614469773,
 8.529182879377434,
 69.78733031674207,
 26.190630048465266,
 14.697815533980583]

#### Indexing, Subsetting, Filtering, & Slicing: Similarities between `array` and `list`

> We have seen differences between arrays and lists.

> Here are also similarities.

In [31]:
%whos

Variable                    Type       Data/Info
------------------------------------------------
addition_of_the_two_lists   list       n=10
earnings_array              ndarray    5: 5 elems, type `float64`, 40 bytes
earnings_list               list       n=5
element_wise_operation      list       n=5
np                          module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy                       module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pe_ratio_array              ndarray    5: 5 elems, type `float64`, 40 bytes
prices_array                ndarray    5: 5 elems, type `float64`, 40 bytes
prices_list                 list       n=5
sample_array                ndarray    5: 5 elems, type `<U32`, 640 bytes
sample_list                 list       n=5
square_of_items             list       n=6


In [32]:
earnings_list

[10.09, 10.28, 2.21, 6.19, 8.24]

In [34]:
earnings_list[1:-1]

[10.28, 2.21, 6.19]

In [36]:
earnings_list[1:-1] == earnings_list[1:4]

True

In [33]:
earnings_array

array([10.09, 10.28,  2.21,  6.19,  8.24])

In [35]:
earnings_array[1:4]

array([10.28,  2.21,  6.19])

In [37]:
len(earnings_array[1:4] == earnings_array[1:-1]
    )

3

In [38]:
earnings_array[1:4] == earnings_array[1:-1] # array([True, True, True])

array([ True,  True,  True])

> Please address the error message above.

### Arrays in NumPy can be `multi`dimensional.

![](ndim.png)
#### How to add image (CLICK HERE TWICE)

> A common form of financial data comes with a rectangular form of data that contains rows and columns. 

> Such data can be represented with two-dimensional arrays.

> To create a two-dimensional array using NumPy, you can use the same function array().

> Instead of providing a single list as your input, let's pass in a list of two lists as your input.

> Here, let's pass earnings and prices to create a two-dimensional array.

In [39]:
pe_array =\
(
    np
    .array(
        [[10.09, 10.28, 2.21,   6.19,   8.24],
         [99.98, 87.68, 154.23, 162.12, 121.11]
        ]
          )
)

print(pe_array)

# Recall that there were two lists of earnings_list and prices_list


[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [40]:
list_in_list =\
    [
        [10.09, 10.28, 2.21,   6.19,   8.24],
        [99.98, 87.68, 154.23, 162.12, 121.11]
    ]

In [41]:
pe_array == np.array(list_in_list)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

> You might want to use `boolean` arrays as well. 

> As you will see below, Boolean arrays are quite useful for subsetting--stay tuned :)

#### Methods in Array

> Like list, array also has many useful methods.

In [42]:
dir(pe_array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

##### array.shape

In [43]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [44]:
pe_array.shape # (2, 5) (row, column)

(2, 5)

In [45]:
np.shape(pe_array)

(2, 5)

In [46]:
pe_array.ndim

2

In [47]:
earnings_array.ndim

1

##### array.size

In [48]:
np.size(pe_array)

10

In [49]:
np.size(earnings_array)

5

In [50]:
earnings_array.size

5

##### array.transpose

In [51]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [53]:
pe_array_transposed =\
(
    np
    .transpose(pe_array)
)

In [54]:
pe_array_transposed.shape

(5, 2)

In [55]:
pe_array_transposed

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

> Remember how to subset nested lists? Subsetting two-dimensional arrays is similar to subsetting nested lists. 

> In a 2D array, the indexing/slicing should be specific to the dimension of the array: **`array[row, column]`**

In [56]:
earnings_array

array([10.09, 10.28,  2.21,  6.19,  8.24])

In [57]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [58]:
earnings_array_twins = pe_array[0, : ]
earnings_array_twins == earnings_array

array([ True,  True,  True,  True,  True])

##### How would you subset `earnings` from the `transposed pe_array`? 

In [59]:
earnings = pe_array_transposed[ : , 0]

print(earnings)

[10.09 10.28  2.21  6.19  8.24]


##### How would you subset `prices` from the `transposed pe_array`? 

In [60]:
prices =\
(
    np
    .transpose(pe_array)
    [ : , 1]
    # R , C
)

print(prices)

[ 99.98  87.68 154.23 162.12 121.11]


##### How would you subset the `earnings and prices for third and forth companies` from the `transposed pe_array`?

In [61]:
pe_array_transposed

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

In [62]:
pe_34 =\
    pe_array_transposed[2:-1, : ]

In [64]:
pe_34 == pe_array_transposed[2:4, : ]

array([[ True,  True],
       [ True,  True]])

In [ ]:
pe_34 == pe_array[ : , 2:4]

> ***Review & Expansion of Your Vocabulary: Below are some useful basics for array.***

In [65]:
# Get Dimension
pe_array.ndim

2

In [66]:
pe_array.ndim == pe_array_transposed.ndim

True

In [67]:
# Get Shape
pe_array.shape

(2, 5)

In [68]:
# Get Type
pe_array.dtype

dtype('float64')

In [70]:
# Get number of elements
pe_array.size # returns 2 * 5 = 10

10

In [71]:
# Get Size (Byte of item)
pe_array.itemsize

8

In [72]:
# Get total size
pe_array.nbytes

80

In [73]:
# Get a specific element [row, column]
pe_array[0, : ]

array([10.09, 10.28,  2.21,  6.19,  8.24])

In [74]:
pe_array[ : , 1]

array([10.28, 87.68])

In [75]:
pe_array_transposed

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

In [76]:
# Getting a little more fancy [startindex:endindex:stepsize]
pe_array_transposed[1 :-1: 2,  0   ]
         # np.array[row,    column]

array([10.28,  6.19])

#### `WARNING`: Please be careful when `copying arrays`!

In [77]:
q =\
(
    np
    .array(
        [3, 5, 7]
    )
)

In [78]:
f = q

In [79]:
q[1] = 9
q

array([3, 9, 7])

In [80]:
f

array([3, 9, 7])

In [81]:
m = np.array([6,2,7])
n = m.copy() # returns a DEEP COPY of the array

m[1] = 100
print(m);print(n)

[  6 100   7]
[6 2 7]


In [82]:
help(pe_array.copy)

Help on built-in function copy:

copy(...) method of numpy.ndarray instance
    a.copy(order='C')
    
    Return a copy of the array.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout of the copy. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible. (Note that this function and :func:`numpy.copy` are very
        similar but have different default values for their order=
        arguments, and this function always passes sub-classes through.)
    
    See also
    --------
    numpy.copy : Similar function with different default behavior
    numpy.copyto
    
    Notes
    -----
    This function is the preferred method for creating an array copy.  The
    function :func:`numpy.copy` is similar, but it defaults to using order 'K',
    and will not pass sub-classes through by default.
    
    Exampl

### Mathematics with NumPy

> **`We all love mathematics`. For a lot more**, [check this out](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

- For example, `linear algebra`, look at [here](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html).

#### Statistics

> Not only can you perform element-wise calculations on NumPy arrays, you can also calculate summary statistics such as range, mean, and standard deviation of arrays using functions from NumPy.

##### Calculating the range (minimum and maximum values)

In [ ]:
print(pe_array)

##### Calculating the mean (`mean`) and standard deviation (`std`)

In [ ]:
earnings_mean = 
print(earnings_mean)

In [ ]:
prices_std = 
print(prices_sd)

##### Generating a sequence of numbers

> Often you may want to create an array of a range of numbers (e.g., 1 to 500) without having to type in every single number. 

> The NumPy function `arange()` is an efficient way to create numeric arrays of a range of numbers--using arange() can be much faster than typing each individual element.

> The arguments for `arange()` include the `start`, `stop`, and `step interval` as follows: `np.arange(start, stop, step)`


In [ ]:

print(ticker_ids)

> How would you create `odd numbers only`?

In [ ]:

print(ticker_ids_odd)

> How would you create **`even`** numbers only then? 

In [ ]:

print(ticker_ids_even)

#### Boolean arrays can be a very powerful way to subset arrays. 

> As a case in point, let's try to identify the earnings that are greater than average from a list of earnings.

> To do so, let's find the mean value of earnings first.

##### How would you index earnings that are lesser than average

> Hint: You might want to create a boolean array first.

In [ ]:

print(boolean_array)

In [ ]:

print(earings_below_mean)

> Boolean array can be used for strings as well. 

> Let's create the names of companies with their associated industry first. 

> Here, your want to find all companies that are categorized as `Investment Services` industry.

##### How would you subset Investment Services industry and print companies in Investment Servecies?

> For your information, there is numpy_financial package that contains a collection of elementary financial functions. 

> It will make your life easier when working with financial values.

> For example, the function .pv(rate, nper, pmt, fv) allows you to calculate the present value of an investment with some parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period
- `fv` The future value of the investment

> You can use this formula in many ways (e.g., you can calculate the present value of future investments in today's dollars).

> Before you run the code above, you should have installed the package `numpy-financial`.

> Here, the present value returned is negative, so we multiply the result by -1

> Similarly, you can also calculate the future value of an investment the following parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period (which is 0 in our example)
- `pv` The present value of the investment

> Here, you can use the function .fv(rate, nper, pmt, pv).

> Note that you should `input a negative value into the pv parameter` if it represents `a negative cash flow (cash going out)`. 

> That is, if you were to compute the future value of an investment, requiring an up-front cash payment, you would need to `input a negative value to the pv parameter` in the function .fv().

# Estimate Your Investment's Future Value

# Estimate the Future Value of Your Friend's Investment

##### Now let's adjust future values of your investment for inflation with the following steps:

**1. forecast the future value of an investment given a rate of return**

**2. discount the future value of the investment by a projected inflation rate**

> Here, we will `utilize both functions .fv() and .pv()` to estimate the projected value of a given investment in today's dollars, adjusted for inflation.

> ***Scenario***: `Investment returning 7% per year for 25 years`

> ***Scenario***: `Inflation rate of 2.5% per year for 25 years`

> `Thank you for working with the script :)`